quick_sort([],[]):-!.
quick_sort([H|T],L1):-
	partition(T,Lt,H,Gt),
	quick_sort(Lt,LtSorted),
	quick_sort(Gt,GtSorted),
	append(LtSorted,[H|GtSorted],L1).
partition([],[],_,[]):-!.
partition([H|T],[H|Lt],X,Gt):-
	H=<X,!,partition(T,Lt,X,Gt).
partition([H|T],Lt,X,[H|Gt]):-
	H>X,partition(T,Lt,X,Gt).
append([],L,L):-!.
append([H|L],L1,[H|L2]):-
	append(L,L1,L2).